name: Tetris Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 3 * * *"   # codziennie o 03:00

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
#        python-version: '3.13.9'
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1

    - name: Install GeckoDriver
      uses: browser-actions/setup-geckodriver@v0.0.0

    - name: Run tests
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          pytest -m smoke --alluredir=allure-results
        else
          pytest -m "not smoke" --alluredir=allure-results

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-screenshots
        path: screenshots/
        if-no-files-found: ignore

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        if-no-files-found: ignore

    - name: Install Allure CLI
      if: always() && hashFiles('allure-results/**') != ''
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre-headless unzip wget
        ALLURE_VERSION=2.27.0
        curl -sSLo allure.zip https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.zip
        unzip -q allure.zip
        sudo mv allure-$ALLURE_VERSION /opt/allure
        echo "/opt/allure/bin" >> $GITHUB_PATH

    - name: Generate Allure report
      if: always() && hashFiles('allure-results/**') != ''
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        if-no-files-found: ignore

    - name: Send email on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "❌ Tetris tests FAILED"
        to: "gblazusiak@gmail.com"
        from: "GitHub Actions"
        body: |
          Testy E2E Tetris zakończyły się błędem.
          Repo: ${{ github.repository }}
          Run: ${{ github.run_url }}
